### ISSUE TITLE
Symmetric key sharing

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#10]
Allow users to securely share symmetric keys over the grd.me servers (assume the grd.me servers are available but otherwise untrusted).

**Comment by winhowes** [comment]
@arnottcr @floryst  do you think it's important to let the sender know whether or not the recipient specifically accepted their key versus acknowledging that their key had been received? The latter is considerably easier to implement and technically the receiver could accept and then delete their key, and the sender would just get the notification that they'd accepted their key, so I feel like it's safe to go with the latter. What are your thoughts?

**Comment by winhowes** [comment]
For documentation's sake: I don't (though I can) notify the user that their key has been received.

**Comment by arnottcr** [comment]
That should be alright, we can see if it causes an issue.

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#15
