### ISSUE TITLE
Stego Public keys

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#12]
We don't want to rely solely on the grd.me servers for publicizing keys, so I propose we stego ppl's public keys in profile pictures on secure "social media" sites.  The first two I would propose are Twitter and GitHub (b/c I believe they allow png's and therefore lossless compression).

Steps:
- [ ] Download a profile picture
- [ ] Stego public key in picture
- [ ] Upload new pic (this may require them giving the browser plugin necessary credentials)
- [ ] Be able to quickly pull key out of picture/detect public key if they visit Twitter/GitHub
- [ ] Allow users to search by Twitter/GitHub handle (we might need to store those handles on grd.me servers, but it would be nice to have a decentralized fallback)

**Comment by arnottcr** [comment]
Sounds great! Let me look into several other services.

**Comment by arnottcr** [comment]
if we implement the server model described in https://github.com/winhowes/grd.me/issues/30, then we can move from stegoing the actual keys, to stegoing the nonce-key-id-thingy

**Comment by winhowes** [comment]
I'm actually still inclined to stego the actual keys for a few reasons:

1. DOS attacks on our servers, would render this useless (granted if the lookup is done from grd me extension -> grd me server -> social media account our servers are still the weak link, but if our servers aren't in the loop, this mitigates that)
2. It functions as a federated key server which means users don't have to rely on our servers (granted it's only for availability) for anything but symmetric key sharing (though this could potentially also be done through other channels)
3. And this is similar to the above, but it encourages decentralization. The nonce approach still focuses on our servers. In an ideal world, we wouldn't have servers and everything would still work seamlessly and securely.

**Comment by arnottcr** [comment]
1) I like the thinking about DOS, realistic issue; good to solve it
2) always like me some federation, and yeah I imagine we could generate symmetric key-share message packets so that you can do this over a chat session. could be useful to allow for public key-sharing over a similar channel for advanced users; twitter post with key.
3) I think it would be much easier to embed a nonce than a key, so it might be good to start with the nonce and move to the key later, again for full decentralization, because I agree if you can have DOS issues you will.

**Comment by winhowes** [comment]
I think a nonce might actually be harder (I already have some hackathon code which does this for a public key in twitter, so I know it's possible. Regarding what you said about key-sharing: totally agrree

**Comment by arnottcr** [comment]
alright, if you can dump the keys into the pics that is likely better; more backend means more places for things to break

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#17
