### ISSUE TITLE
Eliminate line-breakable and commonly escaped characters from decyrptions and tags.

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#14]
This should make decryptions easier to decrypt and reduce tag size

**Comment by arnottcr** [comment]
I really like the concept, as the line breaking that occurs with gpg always annoyed me. However this brings up other issues, what characters can we reliably assume will not be stripped everywhere and if we have access to these characters[I am assuming that we would be using unicode or something else standard], is it possible to use them in addition to the current characters to expand the compression factor? This does require rewriting your encoding
 scheme and that could be harder than just swapping two characters.

Would you prefer a character that is not '~'? I can go for anything just keeping with your ~~crypt~~ style. We can use some unicode here as well to decrease the likely-hood of a collision/false positive.

**Comment by arnottcr** [comment]
P.S. I like the concept of sticking with ascii if we can as it is much safer.

**Comment by winhowes** [comment]
Yeah so I was thinking of:
 + ->  $
 / -> ) 
and using ! to denote that the "ciphertext" is a nonce for a short message (#11) instead of decryptable ciphertext. None of these characters should be line breaking. Right now ciphertexts are base 64 encoded so we can just stick to ascii with these substitutions. 

Regarding the tags, I thought it might be helpful to change them to ~grdme~ and ~.grdme~ for start and end tags respectively. Right now it handles false positives gracefully so it's not that bad and they're also less likely to happen with "grdme".  This also sorta promotes the thing which is cool, and I think it's fairly compact. The character that I really wanted to eliminate was the / in the end tag as it was line breaking.  

Another thought on tags though is just to leave the start tag and switch the end tag out to something else as it doesn't really need the end tags in a lot of cases. This would help minimize the breaking change that this will be. Once we've settled on something and done a more official "release" we can't change the tags

**Comment by arnottcr** [comment]
If you wanted you could use one of the other base64 standards for replacement: https://en.wikipedia.org/wiki/Base64#Implementations_and_history
But it is not too important. Otherwise all your suggestions seem reasonable

Do you want to stay away from small tags for any reason, "~cyhpertext~"? I really like the concept, as they look much cleaner, but realize they might be too undercover.

I realize this should pined down before any sort of official release.

**Comment by winhowes** [comment]
Yeah actually <i>Modified Base64 for XML identifiers (Name)</i> option ( "_" and ":" ) looks like a good option. I'm fine with small tags, I was trying to keep the tags kinda small, but still unique enough to thwart most false positives.  The more false positives the more performance decreases, so I'm totally open to a short tag we just need to decide on something that's unique and should "never" occur in the wild.  So that means the tag must be at least 2 characters if not 3 characters long. Also the end tag should be a little different from the start tag for performance reasons/decryption reasons - there's a few corner cases where having the same tag gets a bit messy.  As for what the tag should be I'm wide open to suggestions

**Comment by winhowes** [comment]
test

**Comment by arnottcr** [comment]
That sounds great, from what I can tell nobody uses the ^?/0x7f character. I sent you an email with the sites I looked at, and the only time that '^?' I found it was the "~^?^?" that I appended to <Winston Howes - Messages.htm>. From what I can tell it is likely that nobody uses ^?, and "<generic printing character>^?" should be pretty unique. Thoughts?

**Comment by floryst** [comment]
Careful using ^? though, some sites likely do strip non-printable ascii. Facebook and Twitter don't, but you can't easily tell.

a	

aa

**Comment by arnottcr** [comment]
I agree with this concern, but in testing it is the only non-printing that nobody strips. Twitter is the worst I have found, and they let that one through.

**Comment by arnottcr** [comment]
also, FLORYST!!!

**Comment by winhowes** [comment]
Welcome Forrest :) I think I'm in the same boat and sticking to 3-4 character printable ascii is probably best.  Although I absolutely love the ui elegance of the ^? character.

**Comment by arnottcr** [comment]
thought: would you want to use ^? on white-listed domains? while we cannot stay that it will work with every service, we could say that it will work with some services, it looks pretty sparse on the web [sites.tar.gz], and some do not strip it

**Comment by winhowes** [comment]
We could, but a whitelist seems a bit tacky/thought of implementing a whitelist doesn't seem too fun, and it makes things weird if you copy and paste to somewhere else that's not on the whitelist

**Comment by arnottcr** [comment]
I agree, and will rescind the request; it would likely be more hassle in the long run.

**Comment by arnottcr** [comment]
So, at this point plan is [code] ~grdMe~ cyphertext ~.grdMe~ [/code]  ??

**Comment by winhowes** [comment]
So, per more discussion with both of you today I have switched the tag from crypt to grdme and the closing tag's / to an exclamation point (!).  I also realized their may potentially be issues with underscore so I was thinking of using ) and : for the two substitutions. Any final thoughts before I push the change?

**Comment by arnottcr** [comment]
Nope, I think that sounds great; did you make a decision about how to deal with old users after the hard-fork?

**Comment by winhowes** [comment]
Yeah, I'll just tell the ppl currently using it to switch over. We'll lose a little bit of work, but not a lot, so it's fine.

**Comment by winhowes** [comment]
For documentation's sake: I changed : to ( due to JSON issue that would have been annoying/slightly slower to work around

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#19
