### ISSUE TITLE
display issue with µBlock

### ISSUE THREAD

**Issue by arnottcr** [winhowes/grd.me#15]
picture!
![grdme_bug](https://cloud.githubusercontent.com/assets/2526260/6005686/337e3b14-ab04-11e4-9c16-574403497773.png)

**Comment by arnottcr** [comment]
I realize that this is a screen shot on nightly, but the issue appears to exist on stable too.

**Comment by winhowes** [comment]
This only happens with µBlock? Seems like it's against my css haha

**Comment by arnottcr** [comment]
I am not running APB anymore, but can check; just thought I would put it in here, not really a priority. More a bug fix for when we have everything else sorted out.

**Comment by winhowes** [comment]
right. Good catch!  I'm running Ad Block Plus (ABP) and it works fine on both chrome and FF. We can look into working this out later down the line. Not high priority

**Comment by arnottcr** [comment]
Good call with the tag; I agree completly

**Comment by arnottcr** [comment]
hey, so something that you did [or did not do] resolved the issues I have been having with µBlock; as such I am closing this issue

**Comment by winhowes** [comment]
haha nice! not sure what it was, but :+1:

**Comment by arnottcr** [comment]
could have been µBlock

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#20
