### ISSUE TITLE
selecting multiple keys

### ISSUE THREAD

**Issue by arnottcr** [winhowes/grd.me#19]
I find myself wanting to use the shift key to select a run of keys and the ctrl key to select additional keys. Both yours and this are valid approaches, I wonder which most users would prefer based on previous UI/UX training?

**Comment by winhowes** [comment]
For the shift key case do you mean holding down the shift key and dragging over an area of keys to select vs ctrl selecting individual keys?

**Comment by arnottcr** [comment]
so, I am thinking shift click will select keys from the currently selected option to the clicked option
and ctrl clicking will add the clicked option to the subset of currently selected options

side effect: shift will need to pick an origin to start from [first click or most recent click] and clicking can deselect some entries

it might just be simpler to stick with the current implementation and see if people are used to or want shift or ctrl [or use both as the same]

**Comment by winhowes** [comment]
sorta like the implementation on google drive? Definitely could be a pain to implement, but if it's better it's worth implementing

**Comment by arnottcr** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Yeah, I think google drive works like that; I can confirm that message
selection in thunderbird works that this:

Ctrl toggles the selection of the clicked item.
Shift selects everything from the most recently clicked item [note this
can be unselected, think select cell then ctrl+click, then shift to
another cell] to the currently clicked item

I think it could be more intuitive to some users, but I am not really
sure what "most" people consider "standard" on the internet.

On 05/02/15 08:51, Winston Howes wrote:
> sorta like the implementation on google drive? Definitely could be a
> pain to implement, but if it's better it's worth implementing
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/winhowes/grd.me/issues/19#issuecomment-73013117>.
> 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iKIEARMKAAYFAlTTMFoACgkQgSpaQHdnUK/ORQIJATuqdpulnYlPC1zaiECRsWgd
NmGA/gaqMUU4CeWCEWYHb6qFN75MznnxIjXON3E3EZyLJKLs/KGaqO3iP487pEMZ
AgkBT6J/qeeGA5I+2L9Ln/G84VIcH0zzhJtAyLEoYsLsmIsmHimv/GURlSxEY2vC
dW0AdTJDcHdw0vWvcAtnN/bRUmc=
=sdZF
-----END PGP SIGNATURE-----

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#24
