### ISSUE TITLE
Add ECC support

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#2]
Be able to use public key crypto. Components:
- [x] Key Pair Generation
- [x] Key Pair Storage
- [x] Key Pair selection in preferences
- [x] Encryption
- [x] ~~Parsing ( @arnottcr  do you think we need a separate tag for this? and would this change how we do #1 ?)~~
- [x] Decryption

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#7
