### ISSUE TITLE
key reupload

### ISSUE THREAD

**Issue by arnottcr** [winhowes/grd.me#20]
this issue is to allow users with the valid private keys to re-upload modified versions of their public keys with new identifiers

separately this can resolve a duplication issue/feature that currently exists

**Comment by winhowes** [comment]
Right now a user can upload their public key with as many identifiers as they want. Are you saying restrict a public/private key pair to one identifier and allow that identifier to be modified?

**Comment by winhowes** [comment]
I've re-interpreted this as syncing pub/priv keys. So if I have published a public key on Chrome and then add that same pub/priv key on Firefox, I can now revoke the key right from Firefox

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#25
