### ISSUE TITLE
keychain export/import

### ISSUE THREAD

**Issue by arnottcr** [winhowes/grd.me#22]
allow a user to export a keyring to a file, encrypted if possible

**Comment by winhowes** [comment]
+1

**Comment by arnottcr** [comment]
I also tried to sync my firefox and chrome keyrings; there is no good export feature, it was a matter of copy, modify and paste. that too should likely be added [clipboard export], if you think it is useful

**Comment by winhowes** [comment]
yep totally agree on all of this

**Comment by arnottcr** [comment]
it looks like you might want to be able to share/export the keyserver bindings, as they did not transfer when I setup chromium

**Comment by winhowes** [comment]
what do you mean by the keyserver bindings? The descriptions?

**Comment by arnottcr** [comment]
I can show that I have the pub and private keys for my asym key, but the
extension does not let me revoke that key, presumably because it does
not know that I uploaded it?

**Comment by winhowes** [comment]
gotcha, yep. Totally agree

**Comment by arnottcr** [comment]
also, I presume that the share key feature will not work with both browsers

**Comment by winhowes** [comment]
I'm not sure what you mean.. You can share keys from both browsers, but I don't think that's what you're saying

**Comment by arnottcr** [comment]
right, but you cannot republish or revoke from browser2

**Comment by arnottcr** [comment]
also, if you share a key with me, it should only go to browser1, right?

**Comment by winhowes** [comment]
In the future you should be able to republish/revoke from browser2.

If I share a symmetric key with you, all your browsers compete for receiving the key and whoever checks for it first gets it (and so do browsers who check at about the same time).

**Comment by arnottcr** [comment]
alright, for pfs we should look at how whispersystems is doing
multidevice support @TheBlueMatt may be of assistance

**Comment by TheBlueMatt** [comment]
https://gist.github.com/TheBlueMatt/d2fcfb78d29faca117f5 is close to what was implemented, with a number of the low-level protocol details replaced with equivalent things.

**Comment by winhowes** [comment]
I like how pfs got dragged into this one :)

**Comment by arnottcr** [comment]
does it not always

**Comment by winhowes** [comment]
Well, so this topic went in a billion directions. I've synced keys between browsers, working on export/import now

**Comment by winhowes** [comment]
This should be now entirely implemented on Firefox

**Comment by winhowes** [comment]
Implemented fully on both browsers. Closing

**Comment by arnottcr** [comment]
awesome

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#27
