### ISSUE TITLE
Key Pinning

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#23]
Allow users to pin keys to a specific domain or domain+path

**Comment by arnottcr** [comment]
we should probably have an option to mangle the current url into a wildcard or regex, and allow the user to specify their own wildcard and regex patterns

**Comment by winhowes** [comment]
Yep, totally agree. (This may be a good task for you to start on if you want - fairly straightforward, but would let you touch quite a bit of code.)

**Comment by arnottcr** [comment]
shit, did not intend to close the issue; I will let you know if I think I can get this done in a timely manner, for now do not let me hold up https://github.com/winhowes/grd.me/milestones/v4

**Comment by winhowes** [comment]
cool, no worries. Milestone v4 is far off, still working on 3 for the next few weeks

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#28
