### ISSUE TITLE
mobile solution

### ISSUE THREAD

**Issue by arnottcr** [winhowes/grd.me#24]
it would be nice to use this service on android/iOS/webOS/ubuntuPhone/etc. however the walled garden of app development means we are going to need to get creative

**Comment by winhowes** [comment]
Yep! I think there may be a way to do it across apps for IOS 8, but I'd have to look more closely to confirm. If you want to start on something in this domain you're more than welcome :)

**Comment by arnottcr** [comment]
I recall you talking about iOS and this previously, so that sounds good;
the target idea is very different: on laptops we are targeting two
pieces of software that interact with almost all of the internet, but
with mobile you must interact with almost all the software that talks to
all the different parts of the internet. there is a fundamental
bottleneck that makes this easier in the browser.

I think that this will need to be done at the operating system level
[ie. something from the OS plugs into every app and does crypto magic;
the keyboard is an easy to do crypttext input, but for cleartext
decryption we will need to monitor all the things <read: difficult>]

**Comment by winhowes** [comment]
right, totally agree. Custom keyboard is easy, I wasn't sure if a keyboard would also have the capability to read whatever's being displayed in an app. An alternate approach (although considerably worse) is to build an app that functions as a browser with a custom keyboard and do everything in there

**Comment by arnottcr** [comment]
I agree, I do not think we can reliably use a keyboard for decryption. Moreover, some users may balk at the concept of not having their preferred keyboard. Finally, if we are willing to go so far as build a browser we could consider a firefox or mobile browser addon?

**Comment by winhowes** [comment]
Yeah mobile browser addons I think work in Android, but I'm not aware of anything for iOS

**Comment by arnottcr** [comment]
While it is not pretty, it looks like the only solution is to create a new app with a UIWebView. http://stackoverflow.com/questions/7708342/ios-safari-support-plugins
Also, this looks like a not chrome feature: https://developer.chrome.com/multidevice/faq

So, we could develop a solution for firefox for android; but at this juncture it seems early.

**Comment by arnottcr** [comment]
could we do this as a website in a website? most of the extension is js, could we download the "extension" run it as a webapp on app.grd.me and build a browser in the browser.

Alright, I will stop right there, because what this idea gains in portability I think it looses in practicality and functionality, especially on low spec hardware. But for its worth, I think this is the only solution to catch all mobile devices. Thoughts?

**Comment by arnottcr** [comment]
launching off point: https://github.com/mozilla/browser.html

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#29
