### ISSUE TITLE
Increase scope to decrypt in shadow DOMs

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#25]
Right now if there's encrypted text in a shadow DOM, grdMe can't find it. Additionally, if you press cmd/ctrl+e in a text box (of any kind) that's located in a shadow DOM, the text will not encrypt.

**Comment by winhowes** [comment]
Encryption now works, the trick is to be able to find decryptions through a shadowDOM, which reduces to the problem of finding all elements with a shadowDOM. If that can be done efficiently, then I can build out decryptions

**Comment by winhowes** [comment]
Might be possible to use the /deep/ selector to pierce through shadow Dom

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#30
