### ISSUE TITLE
Hover on decrypt indicator highlights decrypted text

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#26]
Because you can have nested encryptions or encryptions mixed with plaintext, it'd be nice to highlight (either bolding, underlining, color change, or background-color change) what's decrypted. Italics don't show very clearly and color changes are harder, background-color changes are considerably harder. Bolding increases font width a little bit, which makes for an awkward jump, and underlining isn't super super clear/text might be underlined/bolded anyways. Any suggestions? I'm down for some other indicator as well.

**Comment by arnottcr** [comment]
italics?

**Comment by winhowes** [comment]
Italics don't show very clearly

**Comment by winhowes** [comment]
Another thought would be underline and overline

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#31
