### ISSUE TITLE
Delete published Public/Private keypair without revoke

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#27]
@arnottcr and @floryst Is there value in letting a user delete a published public/private keypair without forcing them to revoke it? Currently you must revoke your key before you can delete it as it becomes impossible to revoke without knowledge of the private key. Of course there are technical ways a user can achieve this, but should this be allowed through the interface?

**Comment by arnottcr** [comment]
most keyservers do not allow deletion, smily revocation. If you want to allow deletion, it can definitely be seen as a feature, but it could also cause DoS issues. My suggestion would be to not allow deletion, unless you have a specific use-case, only revocation.

We could also solve this problem with a textsecure-esk, 100+ prekeys that expire after use. Note, this does require PFS.

**Comment by winhowes** [comment]
Sorry, by deletion, I meant locally. Also, nice label :p

**Comment by arnottcr** [comment]
right, currently we have a single device keyring and as such, if you delete a private key, you probably want to force revocation; but if we implement multiple device support, you may want to remove a key from one device but not the other.

**Comment by winhowes** [comment]
Do you know any good way of detecting multi-device support? Or maybe we just throw a warning up saying if they don't have the key somewhere else then they can't revoke

**Comment by arnottcr** [comment]
honestly, I feel like deletion is not that important a feature, and proving ownership of a public key without a private key is both meaningless and difficult; if you feel like it adds something, it can be done, but you will need to pin down that second method of ownership.

**Comment by winhowes** [comment]
The only reason would be to clear a key off a computer, but you can technically do that by killing the extension... There's not great use for it

**Comment by arnottcr** [comment]
Yeah, that was an issue I ran into; I removed the extension and the keys disappeared. any way to warn users about extension removal?

**Comment by winhowes** [comment]
Yeah once export is implemented I'll put a note in the main page that will show when you add a key or something like that. But I guess this feature isn't really necessary then. Closing.

**Comment by arnottcr** [comment]
Sounds good

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#32
