### ISSUE TITLE
move to federated key-server model

### ISSUE THREAD

**Issue by arnottcr** [winhowes/grd.me#29]
Most pgp implementations allow for several different key-servers, as pgp has no centralized key-server. I think this can be shelved as a long-term goal, as while it prevents some DOS issues it does not solve apparent user-facing issues, or give a big security bump like pfs.

**Comment by arnottcr** [comment]
with this there are two methods we can use: inter-federated server synchronization and no-synchronization. both methods have advantages and disadvantages:

synchro) +allows for redundancy, which is one reason for a federated model; -requires global ids across servers [this is a hard problem, without a namespace of non-trivial size] 
non-syncro) +each server only keeps up with only its own ids; -this model of federation does not add much redundancy, and requires each reference to be "id@keyserver"

I should have come up with a functional solution as described in < https://github.com/winhowes/grd.me/issues/30 > that allows for synchro, as to me, this is the reason to have federation.

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#34
