### ISSUE TITLE
Indicator that text is decrypted.

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#3]
This ticket is both for brainstorming and implementation.  @arnottcr we discussed bolding, italicizing, changing the color of text and even intercepting requests with unencrypted text, blocking them, and replaying them only once the user has determined they want to encrypt their text (could be as simple as clicking a button or pressing enter). Maybe we should add something in the preferences.

**Comment by winhowes** [comment]
Any thoughts on this one?

**Comment by arnottcr** [comment]
I think it would be most helpful to show when text is decrypted, not unencrypted. As it will be easier to control the cleartext.

Bold, bold and dark preen, or bold and italic are my preferences. It would be useful to allow users to select their preference of either or, with some checkboxes in the settings menu if it is not too difficult.

**Comment by winhowes** [comment]
Yeah I think I agree with you on this one. I was thinking rather than bold (because the page might have the text bolded anyways) it might be better to put something like [Decrypted Message] at the beginning, but I'm not 100% sure. There's definitely some elegance to just having the text fit in with the rest of the webpage

**Comment by arnottcr** [comment]
yeah, that should look good; some disclaimer would be good

**Comment by arnottcr** [comment]
I really like the concept of toggle-able settings is a good one, but it may take work. Plus side, it needs to happen at render time for the plain text, so it will never cause a hard fork.

**Comment by winhowes** [comment]
Absolutely with toggling this. The only downside with settings is that too many preferences often leave a user feeling overwhelmed/confused. So I think for now we go one way or the other and then in the future make it toggle-able.

**Comment by winhowes** [comment]
@floryst any thoughts here? To do vs not to do?

**Comment by arnottcr** [comment]
Question: I realize that for some users it can be overwhelming to have a massive settings menu, but I will be honest the first thing I do when I install X application is poke around in the settings menu, read the man pages and generically make it feel like my own. I realize that I am more literate with UIs that the average individual, but assuming you are not required to configure an application before use, do most users really prefer a lack of configurability?

This is a main reason that I dislike AOSP, and cyanogenmod really allows you to tweak the little things. For me, this gives me the feeling [realistically the illusion] that I own or control the software, and it is liberating. I realize that we are all tech literate, so my points here are pretty moot to you, but what are your experiences with others?

**Comment by winhowes** [comment]
I totally agree with that. But I know from my other projects/work people get overwhelmed with preferences. However, right now I'm inclined to add this preference but have it toggled off by default. What would your thoughts be on that? I personally like the "elegance" of the text blending in, but I totally understand a user wanting to be able to differentiate

**Comment by arnottcr** [comment]
I like the concept of having the process/hassle of encrypting messages blend into the background, but I would caution you that there are many case studies where when a user has trouble differentiating operating modes of a security tool, the tool tends to fail. I realize that encryption is still very active in user interaction and there are many other considerations when looking at tool failure, but this can contribute.

I think we should push secure defaults. But I see this as a UI preference, so at the end of the day let us go with the users preferences. [however the hell we figure that out] <side note: do you see good in anonymous reporting, again with the option to turn it off? [I am thinking of how Firefox for Android defaults to reporting, but allows you to turn it off][I can show you this if you are unfamiliar]>

I personally like the "Advanced" or "Debug" menus in settings, it deters most users from touching them, just works out of the box, but allows power users to have their way with an application. This will allow the main settings to be clean and spartan, while keeping in mind that anyone who makes it to the advanced menu will likely not care about the clutter.

**Comment by winhowes** [comment]
Yep that's fair. Once I get user preferences set up I'll add this in

**Comment by winhowes** [comment]
I have this defaulted off. @floryst and @arnottcr what do y'all think?

**Comment by arnottcr** [comment]
Looks great!

**Comment by winhowes** [comment]
After talking with both of y'all we've gone with using the grd me logo as the indicator of decrypted text as it's unlikely to be duplicated and can be shown consistently across all browsers/versions we're supporting while not be too intrusive

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#8
