### ISSUE TITLE
Look into keybase.io integration

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#31]
Can grd me integrate into https://keybase.io for hosting public keys?

**Comment by arnottcr** [comment]
I have submitted a request for an account and mentioned that I am looking to do crypto integration

**Comment by winhowes** [comment]
+1

**Comment by winhowes** [comment]
Looks like this only works with GPG, which as of right now we're undecided on supporting. However, because this requires exclusively gpg, and we're not doing that, I think it would get confusing to use this for some keys but not others. And with the requirement to tweet your key and all that, it just doesn't feel very elegant. Plus stego ( #12 ) will basically take care of this.

**Comment by arnottcr** [comment]
I agree completely; you can do weird shit like encoding your key to look like a gpg key, when in reality it is not. but this seems like a bad idea.

**Comment by winhowes** [comment]
yeah, you'd still have to tweet it and all.. not a fan

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#36
