### ISSUE TITLE
grd.me messaging 

### ISSUE THREAD

**Issue by arnottcr** [winhowes/grd.me#32]
while we are considering pipe dreams, how about we add a messaging service that is interoperable with textsecure/signal; this will require pfs, and we should aim to stay close to the reference axolotl implementation, but I think we can leverage the unused portions of the phone-number namespace, so that we can communicate with textsecure users.

**Comment by winhowes** [comment]
+1 (and pfs hojack :p)

**Comment by winhowes** [comment]
This looks like it's going to be feasible after all with the pfs implementation we've agreed on ;)

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#37
