### ISSUE TITLE
decryption indicator for bold text

### ISSUE THREAD

**Issue by arnottcr** [winhowes/grd.me#34]
so, default for displaying encrypted text is make it bold when hover on icon; how hard would it be to make currently bold text not bold? I realize that at this point we are paying a large cost for a feature that few will use, but I thought it should be asked.

**Comment by winhowes** [comment]
Yeah, no I've thought a lot about this - changing the indicator to just toggle boldness (either on if it doesn't exist, or off it does). This isn't too hard - I'll try to have it done later today

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#39
