### ISSUE TITLE
Sandboxed decrypted styles/fonts not fully imported

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#35]
On Chrome, there's no api I can find to get the CSS for different pseudo classes or to get all the fonts for the page, or for that matter read external stylesheets. It sadly looks like the solution is to do an ajax request from the background script (https://developer.chrome.com/extensions/xhr) for external stylesheets, and then parse them for fonts and styles applied to the elements inserted in the sandboxed decryption and then passed the parsed values into the relevant iframes. This seems so hacky

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#40
