### ISSUE TITLE
Sandboxed decryption performance is dreadful and doesn't work with e10s

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#36]
Once again, FF needs performance help, badly. Regarding e10s, it looks like this may be a bug in FF? Stackoverflow reference for details: http://stackoverflow.com/questions/29033866/content-scripts-dont-attach-to-intercepted-frame-on-firefox-nightly-with-e10s

**Comment by winhowes** [comment]
e10s is a bug in FF itself

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#41
