### ISSUE TITLE
Use unminified libraries

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#37]
It's probably better for everything other than jQuery to use the unminified library, as I've made tweaks to nearly every library, and it makes the code more accessible to review

**Comment by winhowes** [comment]
I've also unminified jQuery as well. If we start noticing additional performance issues (I don't think we will as all the files are local) then I'll reminify as we need to

**Comment by arnottcr** [comment]
I am familiar of the concept of minification, but I leave this in your trusty hands.

**Comment by winhowes** [comment]
The only reason is that it's easier to audit files (especially the ones I've tweaked)

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#42
