### ISSUE TITLE
Getting around 5mb storage limitation

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#39]
Right now we're limited to 5mb of storage on Firefox without doing any file i/o. We're not coming particularly close to using all of that, but it could impair someone who wants a lot of keys/be necessary for pfs ( #7 ). This ticket is both to track the issue as well as to allow us to figure out if there is anyway to do this without having to do file i/o.

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#44
