### ISSUE TITLE
Hybrid Encryption Protocol

### ISSUE THREAD

**Issue by arnottcr** [winhowes/grd.me#6]
Based on how I read your code, you are either using a symmetric encryption algorithm or a elliptic curve one. I suggest moving the elliptic curve crypto to a hybrid protocol, a la pgp. This will allow drastic shrinkage of message size when you have a large number of pubkeys. Symmetric crypto will also decrypt long messages faster, leaving slow ecc to just handle key-material.

https://upload.wikimedia.org/wikipedia/commons/4/4d/PGP_diagram.svg

**Comment by winhowes** [comment]
Sure, but how would the symmetric key be deduced in say a facebook group? It seems each member would have to create a pub/priv keypair and then share their public key with the rest of the group. Each person alert GrdMe who's in the group (unless we want specific code for facebook - which I'd like to avoid) and then GrdMe generate a public key shared between the four memebers? That seems like a lot of hassle. But maybe I'm wrong?

Another idea is to allow pub key sharing to a centralized server (or stego'd in profile pictures on designated networks), allow users to search for others users pub keys and add them to their own keychain, create a share button for each shared key and allow them to share a shared key (encrypted with the recipients pub key and signed with the senders priv key) to a recipient, have the key server store this request to share a key, wait for the recipient to add the senders pub key, and once the receiver has added the key notify the receiver that there's a shared key waiting to be shared with them, and upon acceptance, add the new shared key.  

I think this approach allows for the hybrid encryption, but it allows people to set that up as they need.

**Comment by arnottcr** [comment]
The other thing to consider here is how this impacts forward secrecy. I am really not sure if reusing a symmetric group key would be an issue.

Leaking of a user pubkey would be an issue and allow for decryption of all messages with that key, and generation of all group symmetric keys.

But leaking of a group symmetric key, would only leak all of the messages not the users pubkeys. Theoretically a single group key is a smaller point of failure, but if we assume that it is random having message keys just makes it harder for an attacker to get all the message clear-texts.

The only concern would be a statistical correlation attack, and if you appropriately pad and design your crypto right [I assume that what ever library you are using does this], then it is unlikely that they will be able to correlate usage and decrypt messages. Think work like this: http://www.cs.unc.edu/~amw/resources/hooktonfoniks.pdf

**Comment by winhowes** [comment]
in paragraph 2 you mean a priv key?

**Comment by arnottcr** [comment]
I am not sure how you are doing pubkey/privkey stuff currently, but as per my understanding asymmetric crypto is order of magnitudes slower than symmetric crypto. So, we should be doing all data encryption symmetrically. This means we need to exchange that symmetric key. We can do that via word of mouth, as I think you currently do, or embedded the key in a header, like gpg, or have it stored after some key exchange protocol.

Word of mouth is always nice to allow, I think of it as a fallback. Protocols are messy; I would want Diffie-Hellman, and we would need intercommunication of clients [sounds like a pain in the ass, no?], so this seems like a no. Alternatively, we can do a keyserver setup; this has the advantage of not requiring client intercommunication, but requires some word of mouth/user interaction. Finally, we have embed it in the header and at this point, there is no advantage to actually doing group keys, as each message needs to have its own header gpg style.

**Comment by arnottcr** [comment]
not exactly sure if you implemented ECC directly or ECC-AES hybrid, but this will also likely get rolled into a pfs upgrade. The reasoning for this is solely performance based, aside from for pfs, but I will close this too and we can return to it if necessary. Again, let me know if you think this issue is not resolved.

**Comment by winhowes** [comment]
Right now you can encrypt using just AES or just ECC. ECC is also used to exchange AES keys, so I would argue this hybrid sorta exists (though it may further be rolled up into pfs). Your call on whether to keep this closed, but I think this is done.

**Comment by arnottcr** [comment]
ecc is roughly ~3 orders of magnitude slower than aes, so usually for speed the message is encrypted with aes and the key with ecc; but if it is not an issue we can push it off to pfs. again it only needs to be done if you see issues with ecc speeds. definitely a push off till later.

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#11
