### ISSUE TITLE
perfect forward secrecy

### ISSUE THREAD

**Issue by arnottcr** [winhowes/grd.me#7]
This would be nice, but it seem like a bit of a pipe-dream. I imagine something a la TextSecure, but they have the advantage of not needing to cache ephemeral keys because they only decrypt a message once. For us, we constantly need to decrypt the cypher-text and thus will have a massive database of keys with even larger decryption overhead.
If we can dream up a protocol it would be awesome.

**Comment by arnottcr** [comment]
OK, so I had a wonderful idea: one of the issue with pfs is that it does not allow post hoc additions to a group. Previously I advocated for a nonce be assigned to each message [@floryst and I decided that it should really be a nonce and timestamp to prevent collisions], and we should be able to use that nonce to have users "catch up" new members of groups.

TextSecure already has a way to do group messaging, but members can only see messages after they have been added. What if we allow for a user to catch another up [via either a dedicated channel or a "use facebook as the back end for twitter" approach] via a rebroadcast of the cleartext with a new DH exchange, new ephemeral keys and an old nonce.

So, it would go like this: Bob and Alice are having a conversation they exchange N messages, after each message they delete the ephemeral keys and keep the cleartext, they can display conversations on various services because of the message to nonce paring, then if Alice wanted to add Eve, she could add her to the group [I need to look at how TextSecure does this, but realistically it should just be a "hey, add this public key as a recipient to group X"]  and then send her a "transcript" of the conversation, encrypted with a ephemeral key, ratched per message [or if we want to be really crazy design a multiple cleartext message per crypt block format] derived with DH. This does require that Alice has a DH ½ key for Eve, but otherwise should be 0 RTT.

Thoughts?

**Comment by arnottcr** [comment]
The only issue I see is if we implement message expiration or deleting a message from cache: N days after sending a message the extension will clear it from your database. If this is done it would be impossible to catch people up on sufficiently old or deleted messages. However, if you really do want a message to expire, you likely would not need to share it. Furthermore, if we do expiration and a cache database we need to add support for exporting, the ability to disable it, to change N, to save messages for ever.

Definitely a future concern.

**Comment by winhowes** [comment]
Hey, that's really good! Let me think this one through all the way and I'll try to come up with a list of requirements and implementation steps to see if we missed anything/begin working on making this happen. I'll also check on FF storage as that'll be critical.

**Comment by arnottcr** [comment]
I agree, this will be a complex, multi-step process that will require lots of testing. We should make sure that it supports all the things we need before endeavoring too far.

Redesigns are easy at this point.

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#12
