### ISSUE TITLE
Key Fingerprints

### ISSUE THREAD

**Issue by arnottcr** [winhowes/grd.me#8]
The current method for symmetric keys you have is useful [:N5gaDV7)P3.r5], but could cause some confusion with users: caps/nocaps, what random character is that. The move to either gpg style hexadecimal or tor hidden service style base-32 fingerprint could alleviate that as it will only has one case and numbers. Furthermore the symmetric fingerprints appear to have inconsistent lengths: [pYfK22pA>In=f67d;W8pA:           =n:?73Wdj;E=644              Gfj?:YKKO87S] {there are three passwords there, not sure what is going on}. 

Also the pub/priv keys are all hex, so consistency might be something that users would like.

**Comment by winhowes** [comment]
Regarding length: it generates a random length of 8-32 characters long. 
I did think about just hex, but the initial reason I decided against it was that this feature could double as a password generator for users (several users are using it that way now so I've been told), but maybe the confusion isn't worth "feature"?

**Comment by arnottcr** [comment]
how much user base do you have currently and is JavaScript randomness trustworthy?

Without Wax,
Colin Arnott

**Comment by winhowes** [comment]
User base < 20 (I haven't begun promoting it yet).
Regarding randomness, I believe so: https://developer.mozilla.org/en-US/docs/Web/API/RandomSource.getRandomValues

Also I may switch over to this soon for some crypto: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto

Only downside to this^ is that it supports RSA but not ECC, so we can debate the tradeoff (there may be performance tradeoffs too, but I haven't tested yet).

**Comment by winhowes** [comment]
Update: max shared key length is now 64 and the password generating feature of this has been pretty much killed as the generate button only generates 64 char keys

**Comment by winhowes** [comment]
Closing as I don't think there's an issue here anymore. If there is feel free to re-open

**Comment by arnottcr** [comment]
Yeah, I mostly wanted to stop insecure crypto and it looks like that is being done.

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#13
