### ISSUE TITLE
Overheating/CPU

### ISSUE THREAD

**Issue by arnottcr** [winhowes/grd.me#9]
NFC, but it appears to be an issue.

**Comment by winhowes** [comment]
hmm, yeah I'll keep looking into this. On a fresh version of the latest FF I only have about a 5-8% cpu increase.  And Chrome seems pretty much negligible.  I have a few potential optimizations in mind, but they may cause the crypto-detector to miss a few edge cases.

**Comment by floryst** [comment]
Similar issue on Firefox 35.0.1. Opening a conversation results in ~4-5 sec page freeze.

**Comment by arnottcr** [comment]
We should probably compare the code base for Mailvelope/WebPG, as they either have the same problem, have solved it or cheated.

**Comment by winhowes** [comment]
Yeah I totally agree - I also have a few new optimizations in mind that I'll play around with and report back here on.

**Comment by winhowes** [comment]
Looks like at they're using openpgp.js, https://github.com/openpgpjs/openpgpjs, or something similar in the case of webPG

**Comment by arnottcr** [comment]
If we move to a local database and place nonces with all messages, would it decrease lag due to decryption as it is now a constant time look-up, not a full decrypt operation?

**Comment by winhowes** [comment]
Potentially. Issues with that are: knowing everyone in the group, implementing the secondary channel (though you could also just cache things), and memory. Right now I'm limited to 5mb on Firefox and Chrome. There's a way for me to get more on Chrome that I'll eventually implement, but I still need to figure out Firefox

**Comment by arnottcr** [comment]
can you write things to disk, or are you limited to 5mb total? also, how much text is a 5mb sqlite database?

**Comment by winhowes** [comment]
I think I can create files and so I could read/write things that way (assuming that's true)... Not sure how much text that is. The bigger concern is the secondary channel

**Comment by floryst** [comment]
Exactly what are you doing for decryption? I ask this because it ties up the main UI thread, which is something we don't want. I'm going to try using DOMWorkers to background the decryption task.

**Comment by winhowes** [comment]
^ yep that was one thought I had

**Comment by winhowes** [comment]
So #16 has been implemented. I'm now only seeing a 3-10% cpu increase, but hardly any difference in responsiveness (web worker is keeping decryption from blocking page rendering). Are you  both still seeing performance issues?

**Comment by arnottcr** [comment]
will check tomorrow, busy tonight; sounds awesome though!

**Comment by arnottcr** [comment]
This issue is far from solved on Firefox 35.0, but is much better on firefox-nightly with e10s enabled

**Comment by winhowes** [comment]
Can you see if this is any better on the latest version? It is on my machine, and I think we may be able to close this issue

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#14
